error: 
    status - 500 
    message - Error: User already exist
    at _callee2$ (E:\dd\fundoNotes\src\services\/user.service.js:20:11)
    at tryCatch (E:\dd\fundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\dd\fundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\dd\fundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\dd\fundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\dd\fundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/registration 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-30T18:17:43.555Z"}
